version: '3.8'

services:
  vchord-postgres:
    image: docker.io/tensorchord/vchord-postgres:pg17-v0.4.1
    container_name: vchord-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  pg_data: