version: '3.8'

services:
  vchord-postgres:
    image: docker.io/tensorchord/vchord-postgres:pg17-v0.4.1
    container_name: vchord-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=paper_digest
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  pg_data: