"""create initial tables

Revision ID: 7565b5ff609a
Revises:
Create Date: 2025-05-25 14:46:53.672441

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7565b5ff609a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_setting",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("github_id", sa.Text(), nullable=True),
        sa.Column("pat", sa.Text(), nullable=True),
        sa.Column("repo_name", sa.Text(), nullable=True),
        sa.Column("cron", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "message_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("arxiv_id", sa.Text(), nullable=False),
        sa.Column("repo_name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "reaction_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("arxiv_id", sa.Text(), nullable=False),
        sa.Column("emoji", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reaction_record")
    op.drop_table("message_record")
    op.drop_table("user_setting")
    # ### end Alembic commands ###
