"""add timezone field

Revision ID: 7565b5ff609a
Revises: 
Create Date: 2025-05-25 14:46:53.672441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7565b5ff609a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('github_id', sa.String(length=100), nullable=True, comment='GitHub 用户名，用于绑定 GitHub 账户'),
    sa.Column('pat', sa.Text(), nullable=True, comment='GitHub 访问令牌（Personal Access Token），用于访问 GitHub API'),
    sa.Column('repo_name', sa.String(length=200), nullable=True, comment='GitHub 仓库名，格式通常为 username/repo'),
    sa.Column('frequency', sa.String(length=50), nullable=True, comment='数据抓取频率，例如 daily、weekly 或 cron 表达式'),
    sa.Column('domain', sa.Text(), nullable=True, comment='关注的技术领域或内容标签，如 AI、Security、Web 等'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='用户时区，例如 Asia/Shanghai'),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_setting')
    # ### end Alembic commands ###
